WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.Auth;
using Shared.Models;
using Business.Services;
using Data.Entities;
using Microsoft.AspNetCore.Identity;

namespace WebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserService _userService;
        private readonly SignInManager<MemberEntity> _signInManager;
        public LoginController(UserService userService, SignInManager<MemberEntity> signInManager)
        {
            _userService = userService;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            var vm = new LoginViewModel
            {
                FormData = new LoginFormModel()
            };
            return View(vm);
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var result = await _signInManager.PasswordSignInAsync(vm.FormData.Email, vm.FormData.Password, false, false);
            if(result.Succeeded)
            return RedirectToAction("Projects", "Projects");

            ModelState.AddModelError(string.Empty, "Incorrect email or password.");
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login", "Login");
        }
    }
}

WebApp/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.Auth;
using Shared.Models;
using Business.Services;

namespace WebApp.Controllers
{
    public class SignUpController : Controller
    {
        private readonly UserService _userService;

        public SignUpController(UserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult SignUp()
        {
           
            var vm = new SignUpViewModel();
            return View(vm);
        }


        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            var result = await _userService.CreateAsync(vm.FormData);
            if (!result.Succeeded)
            {
                foreach (var err in result.Errors)
                    ModelState.AddModelError(string.Empty, err.Description);
                return View(vm);
            }

            return RedirectToAction("Login", "Login");
        }
    }
}

WebApp/Views/Login/Login.cshtml
@model LoginViewModel

@{
	Layout = "_CleanLayout";
	ViewData["Title"] = "Login";
}

<div class="surface">
    <h1 class="login-header">Login</h1>
    <form class="login-form" asp-controller="Login" asp-action="Login" method="POST" novalidate>
        <div class="form-fields">
            <label asp-for="FormData.Email">Email</label>
            <input class="form-field" asp-for="FormData.Email" type="email" placeholder="Your email address" required />
            <span asp-validation-for="FormData.Email" style="color:firebrick;"></span>
        </div>

        <div class="form-fields">
            <label asp-for="FormData.Password">Password</label>
            <input class="form-field" asp-for="FormData.Password" type="password" placeholder="Enter your password" required />
            <span asp-validation-for="FormData.Password" style="color:firebrick;"></span>
        </div>

        <div class="form-checkbox-group">
            <label class="form-checkbox">
                <input asp-for="FormData.RememberMe" id="terms-checkbox" class="form-checkbox-input" type="checkbox">
                <span class="form-checkbox-box"></span>
            </label>
            <label asp-for="FormData.RememberMe" class="form-label">Remember me </label>
        </div>


        <button class="btn btn-blue">Log In</button>
    </form>
    <footer class="login-footer">Don't have an account? <a asp-controller="SignUp" asp-action="SignUp">Sign Up</a></footer>
</div>

@await Html.PartialAsync("_ValidationScripts")